[package]
name = "serialization"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rocket]
rocket = "0.5.0-rc.2"
features = ["json", "msgpack", "uuid"]
